
version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: bofa-dvwa
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=dvwa-db
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - dvwa-db
    networks:
      - web-security-lab
    volumes:
      - ./dvwa-config:/var/www/html/config
    restart: unless-stopped

  dvwa-db:
    image: mysql:5.7
    container_name: bofa-dvwa-db
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    ports:
      - "3306:3306"
    networks:
      - web-security-lab
    volumes:
      - dvwa-db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  webgoat:
    image: webgoat/webgoat-8.0
    container_name: bofa-webgoat
    ports:
      - "8081:8080"
    environment:
      - WEBGOAT_HOST=0.0.0.0
      - WEBGOAT_PORT=8080
    networks:
      - web-security-lab
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    container_name: bofa-juice-shop
    ports:
      - "8082:3000"
    networks:
      - web-security-lab
    restart: unless-stopped

  vulnerable-app:
    build: ./vulnerable-app
    container_name: bofa-vulnerable-app
    ports:
      - "8083:80"
    environment:
      - DB_HOST=dvwa-db
      - DB_NAME=vulnerable_app
      - DB_USER=dvwa
      - DB_PASS=p@ssw0rd
    depends_on:
      - dvwa-db
    networks:
      - web-security-lab
    volumes:
      - ./vulnerable-app/src:/var/www/html
    restart: unless-stopped

  zap:
    image: owasp/zap2docker-stable
    container_name: bofa-zap
    ports:
      - "8090:8080"
      - "8091:8090"
    command: zap-webswing.sh
    networks:
      - web-security-lab
    volumes:
      - zap-data:/zap/wrk
    restart: unless-stopped

networks:
  web-security-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  dvwa-db-data:
    driver: local
  zap-data:
    driver: local
