import { useState } from "react";
import { Button } from "@/components/UI/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/UI/dropdown-menu";
import { Code, Download, FileSpreadsheet, FileText, Globe } from "lucide-react";
import { toast } from "sonner";

interface ExecutionData {
  script: string;
  module: string;
  parameters: Record<string, unknown>;
  output: string;
  timestamp: string;
  executionTime: string;
  status: string;
}

interface ReportExporterProps {
  executionData: ExecutionData;
}

const REPORT_GENERATOR = "BOFA Runtime";

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const encodeCsvField = (value: string) => `"${value.replace(/"/g, '""')}"`;

export const ReportExporter = ({ executionData }: ReportExporterProps) => {
  const [isExporting, setIsExporting] = useState(false);

  const generateReport = (format: "json" | "csv" | "txt" | "html") => {
    setIsExporting(true);

    try {
      const generatedAt = new Date().toISOString();
      const reportDate = generatedAt.slice(0, 10);
      const parametersText = JSON.stringify(executionData.parameters, null, 2);
      const outputText = executionData.output ?? "";

      let content = "";
      let filename = `bofa-report-${executionData.script}-${reportDate}`;
      let mimeType = "";

      switch (format) {
        case "json":
          content = JSON.stringify(
            {
              metadata: {
                script: executionData.script,
                module: executionData.module,
                timestamp: executionData.timestamp,
                executionTime: executionData.executionTime,
                status: executionData.status,
                generatedAt,
                generator: REPORT_GENERATOR,
              },
              parameters: executionData.parameters,
              results: {
                output: outputText,
                status: executionData.status,
              },
            },
            null,
            2,
          );
          filename += ".json";
          mimeType = "application/json";
          break;

        case "csv":
          content = "Script,Module,Timestamp,ExecutionTime,Status,Parameters,Output\n";
          content += [
            executionData.script,
            executionData.module,
            executionData.timestamp,
            executionData.executionTime,
            executionData.status,
            JSON.stringify(executionData.parameters),
            outputText,
          ]
            .map(encodeCsvField)
            .join(",");
          filename += ".csv";
          mimeType = "text/csv;charset=utf-8";
          break;

        case "txt":
          content = `BOFA Runtime - Execution Report
======================================

Script: ${executionData.script}
Module: ${executionData.module}
Timestamp: ${executionData.timestamp}
Execution Time: ${executionData.executionTime}
Status: ${executionData.status}

Parameters:
${parametersText}

Output:
${outputText}

======================================
Generated by ${REPORT_GENERATOR} at ${generatedAt}
`;
          filename += ".txt";
          mimeType = "text/plain;charset=utf-8";
          break;

        case "html":
          content = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BOFA Report - ${escapeHtml(executionData.script)}</title>
    <style>
        body { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; margin: 32px; background: #0f172a; color: #e2e8f0; }
        .header { border-bottom: 1px solid #334155; padding-bottom: 16px; margin-bottom: 24px; }
        .section { margin: 20px 0; }
        .card { background: #111827; border: 1px solid #334155; border-radius: 12px; padding: 16px; }
        .meta { color: #7dd3fc; }
        .value { color: #f8fafc; }
        pre { white-space: pre-wrap; word-break: break-word; margin: 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${REPORT_GENERATOR}</h1>
        <h2>Execution Report: ${escapeHtml(executionData.script)}</h2>
    </div>

    <div class="section">
        <h3 class="meta">General Information</h3>
        <div class="card">
            <p><strong>Script:</strong> <span class="value">${escapeHtml(executionData.script)}</span></p>
            <p><strong>Module:</strong> <span class="value">${escapeHtml(executionData.module)}</span></p>
            <p><strong>Timestamp:</strong> <span class="value">${escapeHtml(executionData.timestamp)}</span></p>
            <p><strong>Execution Time:</strong> <span class="value">${escapeHtml(executionData.executionTime)}</span></p>
            <p><strong>Status:</strong> <span class="value">${escapeHtml(executionData.status)}</span></p>
        </div>
    </div>

    <div class="section">
        <h3 class="meta">Parameters</h3>
        <div class="card">
            <pre>${escapeHtml(parametersText)}</pre>
        </div>
    </div>

    <div class="section">
        <h3 class="meta">Output</h3>
        <div class="card">
            <pre>${escapeHtml(outputText)}</pre>
        </div>
    </div>

    <div class="section">
        <p><em>Generated by ${REPORT_GENERATOR} on ${reportDate}</em></p>
    </div>
</body>
</html>`;
          filename += ".html";
          mimeType = "text/html;charset=utf-8";
          break;
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = filename;
      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);

      toast.success(`Reporte ${format.toUpperCase()} descargado correctamente`);
    } catch (error) {
      toast.error(`Error al generar reporte ${format.toUpperCase()}`);
      console.error("Export error:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          disabled={isExporting}
          className="border-cyan-400 text-cyan-400 hover:bg-cyan-400 hover:text-black"
        >
          <Download className="w-4 h-4 mr-2" />
          {isExporting ? "Exportando..." : "Exportar Reporte"}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="bg-gray-800 border-gray-700">
        <DropdownMenuItem
          onClick={() => generateReport("json")}
          className="text-gray-300 hover:bg-gray-700 hover:text-white cursor-pointer"
        >
          <Code className="w-4 h-4 mr-2" />
          JSON (Estructurado)
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => generateReport("csv")}
          className="text-gray-300 hover:bg-gray-700 hover:text-white cursor-pointer"
        >
          <FileSpreadsheet className="w-4 h-4 mr-2" />
          CSV (Excel)
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => generateReport("txt")}
          className="text-gray-300 hover:bg-gray-700 hover:text-white cursor-pointer"
        >
          <FileText className="w-4 h-4 mr-2" />
          TXT (Plano)
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => generateReport("html")}
          className="text-gray-300 hover:bg-gray-700 hover:text-white cursor-pointer"
        >
          <Globe className="w-4 h-4 mr-2" />
          HTML (Web)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
